name: Post Benchmark Results

on:
  workflow_run:
    workflows: ["Run Benchmarks", "Benchmark Start Comment"]
    types: [completed]

jobs:
  post_comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    #   issues: write ???
    steps:
      - name: Download comment id artifact
        if: github.event.workflow_run.event == 'issue_comment'
        uses: actions/download-artifact@v4
        with:
          name: comment-id
          path: .
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Comment Id
        if: github.event.workflow_run.event == 'issue_comment'
        id: get_comment_id
        run: |
          COMMENT_ID=$(cat comment_id.txt)
          echo "COMMENT_ID=$COMMENT_ID" >> $GITHUB_ENV
          echo "Parsed comment_id.txt: COMMENT_ID=$COMMENT_ID"

      - name: Download benchmark artifact
        uses: actions/download-artifact@v4
        with:
          name: benchmark-results
          path: .
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse benchmark_info.json
        id: parse_info
        run: |
          PR_NUMBER=$(jq -r '.pr_number' benchmark_info.json)
          BASE_BRANCH=$(jq -r '.base_branch' benchmark_info.json)
          HEAD_BRANCH=$(jq -r '.head_branch' benchmark_info.json)
          CHECK_RUN_ID=$(jq -r '.check_run_id' benchmark_info.json)
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV
          echo "HEAD_BRANCH=$HEAD_BRANCH" >> $GITHUB_ENV
          echo "CHECK_RUN_ID=$CHECK_RUN_ID" >> $GITHUB_ENV
          echo "Parsed benchmark_info.json:"
          echo "PR_NUMBER=$PR_NUMBER"
          echo "BASE_BRANCH=$BASE_BRANCH"
          echo "HEAD_BRANCH=$HEAD_BRANCH"
          echo "CHECK_RUN_ID=$CHECK_RUN_ID"

      - name: Post benchmark comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const result = fs.readFileSync('comparison.txt', 'utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number(process.env.PR_NUMBER),
              body: `## Benchmark Comparison
              The following table compares the benchmarks from **${process.env.BASE_BRANCH}** (target) and **${process.env.HEAD_BRANCH}** (PR branch):

              \`\`\`
              ${result}
              \`\`\``
            });

      - name: Append to comment to indicate benchmarks have completed
        if: github.event.workflow_run.event == 'issue_comment'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commentId = Number(process.env.COMMENT_ID);
            // Retrieve the current comment body.
            const { data: existingComment } = await github.rest.issues.getComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: commentId
            });
            const appendedText = "\n✅ Benchmarks have completed running, and results have been posted.";
            const newBody = existingComment.body + appendedText;
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: commentId,
              body: newBody
            });
