# .github/workflows/comment-benchmark.yml
name: Comment on Benchmark

on:
  workflow_run:
    workflows: ["Receive Benchmark"]
    types:
      - completed

jobs:
  post_comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      checks: write
    steps:
      - name: Download benchmark artifact
        uses: actions/download-artifact@v4
        with:
          name: benchmark-results
          path: .
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine PR number/info
        id: pr_number
        run: |
          PR_NUM=$(cat pr_number.txt)
          echo "PR_NUMBER=$PR_NUM" >> $GITHUB_ENV
          echo "PR_NUMBER is $PR_NUM"
          BASE=$(grep "BASE_BRANCH" branch_info.txt | cut -d'=' -f2)
          HEAD=$(grep "HEAD_BRANCH" branch_info.txt | cut -d'=' -f2)
          echo "BASE_BRANCH=$BASE" >> $GITHUB_ENV
          echo "HEAD_BRANCH=$HEAD" >> $GITHUB_ENV
          echo "BASE_BRANCH is $BASE and HEAD_BRANCH is $HEAD"

      - name: Post benchmark comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const result = fs.readFileSync('comparison.txt', 'utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number(process.env.PR_NUMBER),
              body: `## Benchmark Comparison
              The following table compares the benchmarks from **${process.env.BASE_BRANCH}** (target) and **${process.env.HEAD_BRANCH}** (PR branch):

              \`\`\`
              ${result}
              \`\`\``
            });

      - name: Read Check Run ID
        id: read_check_id
        run: |
          if [ -f check_run_id.txt ]; then
            echo "CHECK_RUN_ID=$(cat check_run_id.txt)" >> $GITHUB_OUTPUT
          else
            echo "CHECK_RUN_ID=" >> $GITHUB_OUTPUT
          fi

      - name: Complete Benchmark Check Run
        if: ${{ steps.read_check_id.outputs.CHECK_RUN_ID != '' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const checkRunId = fs.readFileSync('check_run_id.txt', 'utf8').trim();
            let summary = 'Benchmark run completed successfully.';
            if (fs.existsSync('comparison.txt')) {
              summary = fs.readFileSync('comparison.txt', 'utf8');
            }
            await github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: Number(checkRunId),
              status: 'completed',
              completed_at: new Date().toISOString(),
              conclusion: 'success',
              output: {
                title: 'Benchmark Run Completed',
                summary: summary
              }
            });
