# .github/workflows/comment-benchmark.yml
name: Comment on Benchmark

on:
  workflow_run:
    workflows: ["Receive Benchmark"]
    types:
      - completed

jobs:
  post_comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      checks: write
    steps:
      - name: Download benchmark artifact
        uses: actions/download-artifact@v4
        with:
          name: benchmark-results
          path: .
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse benchmark_info.json
        id: parse_info
        run: |
          PR_NUMBER=$(jq -r '.pr_number' benchmark_info.json)
          BASE_BRANCH=$(jq -r '.base_branch' benchmark_info.json)
          HEAD_BRANCH=$(jq -r '.head_branch' benchmark_info.json)
          CHECK_RUN_ID=$(jq -r '.check_run_id' benchmark_info.json)
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV
          echo "HEAD_BRANCH=$HEAD_BRANCH" >> $GITHUB_ENV
          echo "CHECK_RUN_ID=$CHECK_RUN_ID" >> $GITHUB_ENV
          echo "Parsed benchmark_info.json:"
          echo "PR_NUMBER=$PR_NUMBER"
          echo "BASE_BRANCH=$BASE_BRANCH"
          echo "HEAD_BRANCH=$HEAD_BRANCH"
          echo "CHECK_RUN_ID=$CHECK_RUN_ID"

      - name: Post benchmark comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const result = fs.readFileSync('comparison.txt', 'utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number(process.env.PR_NUMBER),
              body: `## Benchmark Comparison
              The following table compares the benchmarks from **${process.env.BASE_BRANCH}** (target) and **${process.env.HEAD_BRANCH}** (PR branch):

              \`\`\`
              ${result}
              \`\`\``
            });

      - name: Complete Benchmark Check Run
        if: ${{ env.CHECK_RUN_ID != '' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            let summary = 'Benchmark run completed successfully.';
            if (fs.existsSync('comparison.txt')) {
              summary = fs.readFileSync('comparison.txt', 'utf8');
            }
            await github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: Number(process.env.CHECK_RUN_ID),
              status: 'completed',
              completed_at: new Date().toISOString(),
              conclusion: 'success',
              output: {
                title: 'Benchmark Run Completed',
                summary: summary
              }
            });
