name: Benchmark PR Results

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' &&
      startsWith(github.event.comment.body, 'run benchmarks') &&
      github.event.issue.pull_request)
    permissions:
        pull-requests: write

    steps:
      # Fetch PR details when triggered by an issue comment (not available in the event payload)
      - name: Fetch PR Details
        id: pr_info
        if: github.event_name == 'issue_comment'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            core.setOutput('head', pr.data.head.ref)
            core.setOutput('base', pr.data.base.ref)
            core.setOutput('number', pr.data.number)
            core.setOutput('head_repo', pr.data.head.repo.full_name)

      - name: Determine Branch Names
        run: |
          set -e
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "BASE_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
            echo "HEAD_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          else
            echo "BASE_BRANCH=${{ steps.pr_info.outputs.base }}" >> $GITHUB_ENV
            echo "HEAD_BRANCH=${{ steps.pr_info.outputs.head }}" >> $GITHUB_ENV
          fi

      - name: Checkout Base Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BASE_BRANCH }}
          path: base

      - name: Checkout PR (Head) Branch
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.pr_info.outputs.head_repo || github.event.pull_request.head.repo.full_name }}
          ref: ${{ env.HEAD_BRANCH }}
          path: head

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pyperf
        run: |
          python -m pip install --upgrade pip
          pip install pyperf

      - name: Run Benchmark on Base Branch
        working-directory: base
        run: python benchmarks.py -o ../results-base.json

      - name: Run Benchmark on PR Branch
        working-directory: head
        run: python benchmarks.py -o ../results-head.json

      - name: Compare Benchmarks
        run: python -m pyperf compare_to results-base.json results-head.json --table --table-format=md > comparison.txt

      - name: Post Benchmark Results as PR Comment
        run: gh pr comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number || steps.pr_info.outputs.number }}
          BODY: |
            ## Benchmark Comparison
            The following table compares the benchmarks from **${BASE_BRANCH}** (target) and **${HEAD_BRANCH}** (PR branch):
            $(cat comparison.txt)
